#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Kops version
#
# Usage: kopsenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Kops
# version's `bin' directory is at the front.
#
# For example, if the currently selected Kops version is 0.7.0:
#   kopsenv exec plan
#
# is equivalent to:
#   PATH="$KOPSENV_CONF_DIR/versions/0.7.0/bin:$PATH" kops plan

set -e
[ -n "${KOPSENV_DEBUG}" ] && set -x

source "${KOPSENV_ROOT}/libexec/helpers"

export KOPSENV_VERSION="$(kopsenv-version-name)"

if [ -z "${KOPSENV_VERSION}" ]; then
  warn_and_continue "Trying to install the version of .kops-version"

  "${KOPSENV_ROOT}/libexec/kopsenv-install"
  export KOPSENV_VERSION="$(kopsenv-version-name)"
fi

KOPS_BIN_PATH="${KOPSENV_CONF_DIR}/versions/${KOPSENV_VERSION}/kops"
export PATH="${KOPS_BIN_PATH}:${PATH}"
"${KOPS_BIN_PATH}" "${@}"
